### PR TITLE
fix for new bazel

### PR DESCRIPTION
**Pull request by enricobacis**
I added the `alwayslink = True` to the `cc_library` so that symbols are exported in the `cc_binary`.

### CODE REVIEW

**Comment by luxe** [comment]
@enricobacis which bazel version?

**Comment by enricobacis** [comment]
Hi Trevor, I'm on bazel 2.1.0 and ubuntu 18.04. We tried on 2 machines, and it seems that without the `alwayslink = True` flag, the JNI method is not exposed in the dynamic library. Checking with `nm`, the JNI method is not listed, and in fact when I do `bazel run :Main` I get an error, not about not finding a specific library but about not finding the method.

Also, I use the `bazel_tools` entries in place of the `local_jdk` ones because of a warning that I receive otherwise.

**Comment by luxe** [comment]
thanks.  Your changes work for me too.
I'm also on bazel 2.1.0 and ubuntu 18.04.  

I had encountered a different issue when copying the example into a different directory other than the root of the WORKSPACE (more info here: https://github.com/bazelbuild/bazel/issues/10754).
But that's a different issue unrelated to your fixes.

**Comment by hlopko** [comment]
Hey Enrico! :) 

Thanks for doing this!

**Comment by enricobacis** [comment]
Hi Marcel! Thanks for merging this!

Have a nice evening, I'm sure we will meet soon ;)

**Pull request merged**
